package trv.triviaapp.ui;

import javax.swing.SwingUtilities;
import trv.triviaapp.controller.TriviaController;
import trv.triviaapp.model.Question;

/**
 * GUI form for displaying true/false questions in a trivia game.
 */
public class TrueFalseForm extends javax.swing.JFrame {
    private TriviaController controller;
    private Question currentQuestion;
    
    /**
     * Constructor that initializes the form with the controller.
     * @param controller the TriviaController that manages game logic.
     */
    public TrueFalseForm(TriviaController controller) {
        this.controller = controller;
        initComponents();
        this.setLocationRelativeTo(null); // Center the window
    }

    /**
     * Sets the current question to be displayed in the form.
     * @param question the question object containing the text.
     */
    public void setQuestion(Question question) {
        this.currentQuestion = question;

        resetOptions();

        txtQuestion.setEditable(true);
        txtQuestion.setText(question.getQuestion());
        txtQuestion.setEditable(false); // Prevent editing

        int [] data = controller.getData();
        lblCounter.setText((data[0]+1) + "/" + data[1]);        
        
        this.revalidate();
        this.repaint();
    }

    /**
     * Enables both true and false options (used before a new question is shown).
     */
    public void resetOptions() {
        lblOptionFalse.setEnabled(true);
        lblOptionTrue.setEnabled(true);
    }

    /**
     * Updates the UI components (useful after changing the look and feel).
     */
    public void updateUI() {
        SwingUtilities.updateComponentTreeUI(this);
        this.invalidate();
        this.validate();
        this.repaint();
    }

    /**
     * Disables both true and false options to prevent further clicks.
     */
    public void disableAllOptions() {
        lblOptionTrue.setEnabled(false);
        lblOptionFalse.setEnabled(false);
    }

    /**
     * Initializes the components of the form (auto-generated by GUI builder).
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        panelOption2 = new javax.swing.JPanel();
        lblOptionTrue = new javax.swing.JLabel();
        panelOption1 = new javax.swing.JPanel();
        lblOptionFalse = new javax.swing.JLabel();
        lblCounter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelBackground.setBackground(new java.awt.Color(65, 0, 128));
        jPanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQuestion.setColumns(20);
        txtQuestion.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        jPanelBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 540, 140));

        panelOption2.setBackground(new java.awt.Color(129, 0, 127));

        lblOptionTrue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblOptionTrue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOptionTrue.setText("True");
        lblOptionTrue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOptionTrueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelOption2Layout = new javax.swing.GroupLayout(panelOption2);
        panelOption2.setLayout(panelOption2Layout);
        panelOption2Layout.setHorizontalGroup(
            panelOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOptionTrue, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        panelOption2Layout.setVerticalGroup(
            panelOption2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOptionTrue, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jPanelBackground.add(panelOption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 260, 90));

        panelOption1.setBackground(new java.awt.Color(129, 0, 127));

        lblOptionFalse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblOptionFalse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOptionFalse.setText("False");
        lblOptionFalse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOptionFalseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelOption1Layout = new javax.swing.GroupLayout(panelOption1);
        panelOption1.setLayout(panelOption1Layout);
        panelOption1Layout.setHorizontalGroup(
            panelOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOptionFalse, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        panelOption1Layout.setVerticalGroup(
            panelOption1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOptionFalse, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jPanelBackground.add(panelOption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 260, 90));

        lblCounter.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCounter.setText("../..");
        jPanelBackground.add(lblCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOptionTrueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOptionTrueMouseClicked
        controller.submitAnswer(lblOptionTrue.getText());
        disableAllOptions();
    }//GEN-LAST:event_lblOptionTrueMouseClicked

    private void lblOptionFalseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOptionFalseMouseClicked
        controller.submitAnswer(lblOptionFalse.getText());
        disableAllOptions();
    }//GEN-LAST:event_lblOptionFalseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrueFalseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrueFalseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrueFalseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrueFalseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCounter;
    private javax.swing.JLabel lblOptionFalse;
    private javax.swing.JLabel lblOptionTrue;
    private javax.swing.JPanel panelOption1;
    private javax.swing.JPanel panelOption2;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables
}
